# Definition

***Warning:* This is a work in progress, i.e., currently just a collection of unstructured information.**

## What are Archetypes?

We define archetypes as the product of the essentialisation of the space created by the fundamental axes that structure a cognitive system. These axes create layers of opposed poles that are tied to important concepts for adaptation and survival. For example, one possible axis would give rise to the concepts (the centroids of the spaces created by this axis) of life and death, a distinction arguably critical to Humans. In this example, the process of archetypalisation would essentialise these spaces (or proto-concepts), for instance to features or symbols (e.g., the tree, the heart, the skull). 

But these examples are not necessarily "true" archetypes. Indeed, compared to other results of essentialisation, true archetypes present some specific characteristics. Their ontogenic origin can be traced to the early stages of development (roughly equivalent to children in Humans). They are usually primitive (or "raw"), in the sense that they require minimal cognitive ability to be created. They are efficient, encapsulating and conveying complex meaning in the most effective form. They are important for adaptation and survival, allowing for the easy integration of important notions. They are meta-stable relative to a given spatio-temporal context, meaning that individuals growing in a similar environment (without necessarily communicating between them) should exhibit similar forms of archetypes (as these are essentialised in relation to the interaction between an individual and its environment).  

As a consequence, archetypes (in our definition) are not universal and can present variations in their presentations depending on the geographical and temporal context. Nevertheless, the proto-concepts that they are attached to might be similar. For example, the essentialisation of the concept of life and death might manifest under different forms: a society were a given animal is the main cause of death may use it as its symbol, compared to another society in which death is best exemplified through something else. That being said, a society where death does not exist (in which the life and death distinction is useless) might not display any (pseudo)archetype for it.

Archetypes are neither collective *per se*. They do not emanate or emerge from some shared memories or history, other than the similarities of our lives. They are deeply and inherently individual, and their collective aspect (as they are usually shared within a given culture) is merely a reflection of the ontogenic and evolutionary redundancies.

## Essentialisation

Essentialisation is the core mechanism underlying the existence and creation of archetypes. Essentialisation is in general achieved either through biomorphism (in particular, anthropomorphism), giving Human or animal-like aspect to objects, or symbolification, reducing a concept to a (usually visual) symbol. The mode of essentialisation might depend on cognitive abilities (abstraction / imagery abilities) and environment (prevalence of natural or abstract objects).


archetype primaire (innés) = génétique, adaptive
archétype secondaire (activés) = activés par l'expérience precoces (sur un modèle epigenetique)
archétype tertiaires (créés) : crée et entrenues par la culture 
