# Archetypes and the Brain

***Warning:* This is a work in progress, i.e., currently just a collection of unstructured information.**

Archetypes are a tangible reflection of a neuropsychological proto-structure. But do they have a biological existence?

## Origin

Are the archetypes innate? No, (altough they might have been favoured by evolution); they stem out of the redunduncies of existence.

## Archetypes as Neurocognitive Invariants

contrary to Jung, these archetypes are not originating from some collective unconscious, but rather are created and maintained by the ontology of the individual, and patterns are crystilised out of the répétition and similarity accross individual ontologies (e.g., the presnece of a fatherly and a motherly figure, etc.)



## Neurological Substrate

Attempts have been made to map archetypes unto brain structures [@samuels2003jung]. For instance, @rossi1977cerebral suggested that one could locate the archetypes in the right cerebral hemisphere, based on the idea that the left hemisphe would be primarily verbal and associational, and the right primarily visuospatial and apperceptive. In light of the current neuroscientific data, these theories appear as nonsensical and naive.

That being said, if archetypes are engrammed into the cognitive system, a biological basis has to exist. One potential answer is to reframe archetypism under the predictive coding framework. As such, archetypes could be seen as meta-priors.

