## Critiques and Problems of Archetypes


Until now, we tred presenting the different views and claims neutrally. However, 
<!-- the reader should keep in mind that many of the assertions have not been scientifically validated. -->

One major stream of critiques is directed at Jung himself, for his alleged ethnocentrism, racism, colonial mindset, and sympathies for the Nazi regime (see this REFERENCE for an overview of the critiques). But what is more relevant for the topic at hand are the issues pertaining to his developpment of the concept of archetypes.


### Issues With Jungian Archetypes


<!-- https://www.singingtotheplants.com/2009/09/collective-unconscious/ -->

<!-- Describe the excellent work by @lequellec2013jung. -->

<!-- https://www.hgi.org.uk/resources/delve-our-extensive-library/interviews/mysterious-jung-his-cult-lies-he-told-and-occult -->

### Issues with the concept itself

Circular reasoning.

### Future Directions

The psychologist James Hillman suggested to eliminate the noun archetype altogether, while preserving the adjective *archetypal*.

Another possibility is to try to redefine archetypes precisely, and redefine them in a way that makes compatible with scientific investigation and useful for theory or practice (as archetypes are one of the tools used in psychoanalytical therapy). This is the aim of the next chapter.
