# Archetypes and Modern Science

> _We Jungians cannot go on basing our theory of archetypes on scientific assumptions which have been falsified by more recent research if we do not want to run the risk of becoming ridiculous in the scientific world._
>
> `r tufte::quote_footer('--- Christian Roesler (2012)')`

To summarize, the Jungian psychodynamic approach postulates that there is an unconscious but universal part of the mind that would be partly made of "empty" shapes that, when filled with content, would give rise to recurrent images that give rise to a strong subjective impression (and assessed as deep and meaningful). Naturally, the fact that archetypes *per se* are by nature inaccessible, and that their only manifest and indirect "proof" of existence are a category which only defining property is particular subjective experience, poses a challenge for scientific investigation. 

First of all, submitting psychodynamic approaches to scientific validation is, despite what their respective authors claimed, misled. 

<!-- Jung did throughout most of his life was to make psychological interpretations of texts, dreams and fantasies. His practical approach to psychology was hermeneutical. -->

<!-- The German philosopher Habermas (1968) pointed out the same for Freud’s psychoanalysis and called it the ‘szientistische Selbstmißverstandnis’ ¨ (self-misunderstanding as a science) of psychoanalysis -->

If we unpack the issues, there are problems related to 1) the unconscious, 2) collective and universal features, and 3) inheritability of archetypes, 4) epistemological issues.

## From Theory to Application

Following Jung's work, many archetype theorists have adopted a "bottom-up approach", i.e., starting from observations to infer the cause (the nature of archetypes). Observations are gathered by exploring various cultures, myths, religions or the depths of Human's psyche (using tools of pseudo-access such as psychoanalysis or hypnosis). In this framework, the archetypist's role is to assemble and integrate the interpretations emerging from these observations, in a theory that could be applied to explain these observations.

In this book, we will take the opposite approach. Based on scientific knowledge about evolution, biology and neuroscience, we will outline a plausible framework, that we will then test on observations and facts.




## A Falsifiable Theory


The fundamental issue of psychoanalysis is that it is not a scientific theory, which requires a possibility of falsification. For example, Newton's law of gravity could easily be falsified if, for instance, the apple did not fall from the tree but levitated there (and it has been later falsified by astronomical observations, and eventually replaced, by Einstein's set of theories). On the contrary, every observation is evidence in favour of psychoanalysis, and the same can unfortunately be said for Jungian's approach.

This pseudoscientific nature is particularly relevant for the Jungian conceptualisation of archetypes, which suffers from a structural and inherent unscientificalness. In metaphorical terms, we could say that it is an *ouroboros* (the symbol of a dragon/serpent eating its own tail): the natural "consequences" of archetypes (i.e., the manifest patterns and motifs that we observe in myths, stories, religions...) are also, in theory, the "cause" of them. In other words, the existence of numerous instances of wise old men is brandished as the one of the only possible manifest proof for the existence of the archetype of the wise old man. And the redundancy of this motif is also what perpetuates its archetypal nature. The serpent eats itself, and the existence of this archetype, as it is tied only to a given existing observation, is unfalsifiable. On an abstract level, if *B* is the cause of *C*, scientists would investigate the cause(s) and origin(s) of *B*, let it be *A*, so that *A* &#8594; *B* &#8594; *C*. The system has a clear causal structure. For archetypes, the current approach suggests that *A* <-> *B*: archetypal images are made *manifest* (observable, and thus measurable) as they are filled with a idiosyncratic content (depending on the culture, beliefs, personal experience etc.). Hence, we cannot demonstrate that archetypes do not exist, because every motif is potentially a proof in favour of an archetype.


Therefore, how to scientifically test (and refute) archetypism is the core question of any scientific approach to archetypism. Thus, after outlining our perspective on archetypes in the following chapters, we will propose practical ways to assess their existence and role in society and individuals.




## Critiques and Problems of Archetypes

<!-- See [Roesler 2012](https://cgjung.de/wp-content/uploads/2019/02/Archetypes.pdf): Are archetypes transmitted more by culture than biology? Questions arising from conceptualizations of the archetype. -->

Until now, we tred presenting the different views and claims neutrally. However, 
<!-- the reader should keep in mind that many of the assertions have not been scientifically validated. -->

One major stream of critiques is directed at Jung himself, for his alleged ethnocentrism, racism, colonial mindset, and sympathies for the Nazi regime (see this REFERENCE for an overview of the critiques). But what is more relevant for the topic at hand are the issues pertaining to his developpment of the concept of archetypes.


### Issues With Jungian Archetypes

Jung never discusses the inconsistencies and contradictions in his theory.


<!-- https://www.singingtotheplants.com/2009/09/collective-unconscious/ -->

<!-- Describe the excellent work by @lequellec2013jung. -->

<!-- https://www.hgi.org.uk/resources/delve-our-extensive-library/interviews/mysterious-jung-his-cult-lies-he-told-and-occult -->


The issue of cryptomnesia. In order to state that the archetype is innate and not learned, Jung had to claim, for all of his cases, that there had been no prior contact with the archetypal image or idea by the person producing it. However, this turned out to be either untrue, doubtful or not substantiated enough. [@roesler2012archetypes]


Jung defines archetype-as-such as content free, but it is difficult to assume mental concepts which carry no content. As Knox argues, the archetypal forms to which Jung refers imply symbolic meanings and therefore, mental content [@knox2003archetype, p. 33].

<!-- Interestingly, while the archetypal images are (understandably) the main focus and interest of subsequent authors, it is important to note that Jung himself warned against such simplification. Such *"definite mythological images of motifs [...] are nothing more than conscious representations; it would be absurd to assume that such variable representations could be inherited"*. Again, the true archetypes for Jung were their deeper, instinctual, fluid sources – *"the 'archaic remnants', which I call 'archetypes' or 'primordial images'"* [@jung1964approaching]. -->

<!-- https://cgjung.de/wp-content/uploads/2019/02/Archetypes.pdf -->


### Issues with the concept itself

Circular reasoning.

Universality is a prerequisite for the existence and definition of archetypes and its usage in clinical practice [@roesler2012archetypes]. Unfortunately, no evidence exist to support such idea, nor have any theories (e.g., genetics, epigenetics, ) yet provided a satisfying theoretical basis to explain how this universality comes into existence.

> we Jungians cannot go on basing our theory of archetypes on scientific assumptions which have been falsified by more recent research if we do not want to run the risk of becoming ridiculous in the scientific world. It is important that we stop arguing that archetypes are transmitted genetically if we want to be taken seriously. [@roesler2012archetypes]


### Future Directions

The James Hillman suggested to eliminate the noun archetype altogether, while preserving the adjective *archetypal*.

Another possibility is to try to redefine archetypes precisely, and redefine them in a way that makes compatible with scientific investigation and useful for theory or practice (as archetypes are one of the tools used in psychoanalytical therapy). This is the aim of the next chapter.



## Biology


Interestingly, Jung, similarly to Freud, always made great efforts to portray his concepts as rooted in biology (after all, both were physicians by training), for instance in the case of archetypes, via supposed mechanisms of biological inheritance [which is no longer supported by modern genetics modern genetics; @roesler2012archetypes]. However, the most notable advances in that area were done by their followers, trying to adapt and accommodate psychodynamic concepts with discovers made in neuroscience and modern psychology.


### Genetics

[@roesler2012archetypes]

### Epigenetics

[@roesler2012archetypes]

## Neuroscience

Archetypes are a tangible reflection of a neuropsychological proto-structure. But do they have a biological existence?

### Origin

Are the archetypes innate? No, (altough they might have been favoured by evolution); they stem out of the redunduncies of existence.

### Archetypes as Neurocognitive Invariants

contrary to Jung, these archetypes are not originating from some collective unconscious, but rather are created and maintained by the ontology of the individual, and patterns are crystilised out of the répétition and similarity accross individual ontologies (e.g., the presnece of a fatherly and a motherly figure, etc.)



### Neurological Substrate

Attempts have been made to map archetypes unto brain structures [@samuels2003jung]. For instance, @rossi1977cerebral suggested that one could locate the archetypes in the right cerebral hemisphere, based on the idea that the left hemisphe would be primarily verbal and associational, and the right primarily visuospatial and apperceptive. In light of the current neuroscientific data, these theories appear as nonsensical and naive.

That being said, if archetypes are engrammed into the cognitive system, a biological basis has to exist. One potential answer is to reframe archetypism under the predictive coding framework. As such, archetypes could be seen as meta-priors.


### Predictive Coding

Archetypes as priors.

## Psychology

The archetypal framework developped in this book is by essence reductionist, exploring the abstract core features of cognition and essentializing them to concepts of pure abstraction. As such, archetypes do not directly relate to individual psychology, nor to anything tangible.

### Dreams

A large part of Jungian's model is rooted in the analysis of dreams. The (still lasting) popularity of his approach could be related to its imcreased straightforwardness, as compared to Freudian's more convoluted interpretation framework. Contrary to the latter, Jung believed that the meaning of a dream was directly present in the manifest content of the dream (i.e., what the dreamer experiences). 


Jung distinguished two types of dreams: the archetypal and the everyday [@cann1986jungian]. Everyday dreams find their origin in the personal unconscious and are related to personal matters. Archetypal dreams, on the opposite, originate from the collective unconscious, and deal with universal themes. The best criterion for distinguishing archetypal dreams appears to be their lack of "everydayness" [@kluger1975archetypal; @cann1986jungian].


### Personality

Jung classified personality types by using three pairs of opposites: *introversion* (directing interest and attention towards internal experiences and processes. ) - *extraversion* (directing interest and attention towards people and things in the external world), *sensation* (perceiving the presence and qualities of facts directly through the senses) - *intuition* (perceiving the relations in events and situations unconsciously), and *thinking* (organizing and judging experience on the basis of analysis and logic) - *feeling* (organizing and judging experience on the basis of importance, values, likes, and dislikes). 

This model of personality is somewhat not too distant from modern accounts (such as the Big Five and its successors), especially regarding the introversion-extraversion axis. However, a distinction is to be made, as Jung's model does not incorporate one of the other personality dimension, namely *neurosis* (i.e., emotional instability), as such. Instead, Jung conceptualises neurosis as the opposite of psychosis, both related to the pattern relationship between the conscious and the unconscious. In summary, people with neurosis would be out of contact with the collective unconscious, whereas people with psychosis are too much in contact with it, at the expense of external reality (hence the strong interest of Jung for patients suffering from schizophrenia). Additionally, contrary to more recent models in which personality dimensions are conceptualised as to a large extent indepedendent (i.e., all combinations of personality traits are possible), the expression of Jungian's neurosis depends on other dimensions. For instance, the typical form of neurosis for people with high introverion is anxiety, and hysteria (characterized by high activity levels, physical complaints, and emotional volatility) for extroverts.

Importantly for our topic, archetypes have not been directly connected with any personality profiles. Instead, Jung and his followers attempted to use their own conceptualisation of personality profiles (i.e., and of their configuration regarding the relationship between the conscious and the unconscious) to gather evidence in favour of their theory. For instance, by showing that people with high intuitiveness and low neuroticism recall more archetypal dreams [i.e., dreams with less "everydayness"; @kluger1975archetypal; @cann1986jungian].



### Archetypes as the Self

The serpent is as the Self. Always changing, but always the same.



### Archetypes as Personality Clusters


### Archetypes as Heuristics

A more process-based and fluid framework.

One could define an archetype is a basic frame facilitating a basic, instinctive, and intuitive understanding of a concept or a personality. This definition brings it close to a key concept in psychology, heuristics.



## Limitations

One practical limitation of our approach is that some of the data is already known, which makes it hard to blindly derive predictions from a model that one could later test. For instance, if we postulate that archetypical motives could be present within the similarities of myths, stories and religions, it is hard not to be inspired and influenced by the existing facts. Even with good theoretical reasons, it appears as complicated to postulate the existence of a given archetypal motif if we know in advance that its presence in Human productions is very seldom. Our cultural environment influences its theorization. Although it is also the case in other scientific fields, it might be stronger when it comes to archetypes, as they are particularly deeply connected with cultural manifestations.


Another, more fundamental, angle of attack concerns the practical value of over-specific and over-generic archetypes. As we have seen in previous examples, some authors proposed a list of archetypes so vast that their usefulness and relevance as a scientific concept is limited. On the other hand, others authors (including Jung) emphasize quite generic figures, such as "the father" or "the mother". The issue with this is that the fact that that these figures and concepts are critically important in Human culture cannot be used as a evidence in favour of their archetypicity. Yes, a loving mother and a fearless father are common tropes in Human existence. One could thus wonder about the relevance of creating a whole theory around them. Thus, finding the right level, the sweet spot, between specificity and genericity, appears as an important challenge for our endeveour.

<!-- The goal of the archetypist is to study these and uncover their role in society or individuals. -->

<!-- Examples of experiments: -->

<!-- - Child remembers a story and its content where the protagnositc are congruent with archetypes? -->
<!-- - Pseudo-role playing game where participanats have to decide which archetypal character to go ask for specific archetypical questions  -->
<!-- - Comparative exploration of proto-religions -->


