# A Scientific Archetypism

A scientific approach to archetypes must be based on a plausible conceptual framework. In the previous chapter, we outlined the state of science in its relationship to archetypes, emphasizing important limitations. There is simply no scientific theory that would justify the existence of archetypes as they are defined in Jungian approaches.



## Commonalities of Being


### Universal Truths about Humans 

One of the semi-hidden assumption behind archetypes is that there is some commonalities to Human experience, and that recurring patterns of thought and behaviour are not the mere result of chance or random evolution, but rather has a common origin, whether it is "innate" (as a core property of our mental functioning) or "acquired" through exchanges and learning (or, as often, a mix of both). Thus, it is unsuprising that one of the main line of critique of archetypes (and also, of comparative mythology), aims at this will to find, and bias in favour of, shared characteristics rather than differences and nuances.

Where does a neuroscientific archetypism place itself? As per its name, the assumption that we hold is that archetypes, if they exist, are products of the brain and, by extension, are tied to the structural similarities that we share as Humans.

## Symbiotic relation between archetypal ideas and their representations (archetypal symbol)



## World axes: several axes that structure the mental world, more or less universal

We, humans, are beings evolving in a complex psychological environment. Understanding one's place and position in this abstract space is a question of adaptation and, ultimately, survival. In order to approach this, one must figure out the boundaries of the psychological world, which could be understood as a multidimensional space with more or less important dimensions, which structure our world. To be able to locate along these axes, it is useful to assign antagonistic concepts as their opposite poles. Typically, it is centrally important to discriminate between two extreme states such as what is alive and what is dead. Death, and (exacerbated) life become the two poles of an axis, allowing us to think about (i.e., ordering and structuring) more complex states, like being sick, old, in gestation, or the nature of different entities like other animals, plants, minerals, and everything in between.





