# Archetypal stories and motifs

***Warning:* This is a work in progress, i.e., currently just a collection of unstructured information.**


Common motives in religions and myths beg the question of the existence or plausibility of archetypal stories.


## The Battle against the Serpent

<!-- New myths: Le serpent représente tout système opprrssif et dangereux, autrefois des monstres, maintenant des systèmes societaux (Orwell, Huxlay et les nouveaux mythes)  -->

<!-- The serpent seed theory -->

## Gods from Above

<!-- nouveau mythes: alien (nouveaux dieux venu de l'au-delà rationalisé), reptilian (existence d'être maléfiques cachés parmi nous)  -->

## Underground Place


## Cataclysm

### Flood Myths

Ancient flood (end of the glacial era) and recent flood (minnoean period).

The historicity of a massive volcanic explosion happening in the Mediteranean is fairly plausible, which is line with the inclusion of this motif in most of the mediteraneean civilizations. The eruption would have been so strong that it would have clouded the sky with ashes all over the planet, creating a sudden drop of temperatures (possibly causing a so-called nuclear winter). It is interesting that in other parts of the world, the mythological cataclysm takes the form of a great winter (*Fimbulvetr* in norse mythology)

See also in Aztec / Incas / Maya Mythology

<!-- See also "Extreme weather events of 535–536" -->

## Sacrifice of God

### Prometheus

### Jesus

## Flood Survivor

### Atrahasis

### Utnapishtim

### Noah




## Murder of sibling

What's the symbolic of that?

### Set and Osiris



### Cain and Abel (Biblic)

Cain was the older brother (first-born), a "tiller of the ground" (a farmer, and a builder), whereas Abel was a shepherd, connected with the animals and nature (however, as a leader of it).


The Cainites: a sect worshiping Cain.

Eve then received a third son, which name has been translated to "Seth" in English. Note that there is no reason to connect this figure (which Hebrew name would sound closer to *sheyth*) to the Egyptian god Set (which name was heard and recorded as *sutash* or *sutakh* by ancient Babylonians who were in contact with Egypt).

## Baldr and Hodr (Norse)
