on:
  push:
    branches:
      - master
      
name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown"), dependencies = TRUE)'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", "md_document", output_file = "README.md")'
      - name: Commit results
        run: |
          git fetch origin
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
