on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
name: Render Book

jobs:
  render:
    name: Render Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("blogdown", "bookdown"), dependencies = TRUE)'
      - name: Render Gitbook
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
      - name: Commit results
        run: |
          git commit -m 'Push gitbook' --docs || echo "No changes to commit"
          git push origin || echo "No changes to commit"
