on:
  push:
    branches:
      - master
      
name: Render Book

jobs:
  render:
    name: Render Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "blogdown", "bookdown", "tufte"), dependencies = TRUE)'
      - name: Render Gitbook
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
      - name: Commit results
        run: |
          git fetch origin
          git commit -m 'Push gitbook' docs || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      #- name: Render PDF
      #  run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book", output_dir = "./pdf/")'
      #- name: Commit results
      #  run: |
      #    git commit -m 'Push pdf' --pdf || echo "No changes to commit"
      #    git push origin || echo "No changes to commit"
